"""A* Conferences database with requirements and templates."""

from dataclasses import dataclass
from typing import Optional


@dataclass
class ConferenceRequirements:
    name: str
    full_name: str
    venue_type: str
    page_limit: int
    page_limit_with_refs: Optional[int]
    paper_size: str
    margins: dict[str, float]
    font_family: str
    font_size: int
    columns: int
    abstract_word_limit: int
    citation_style: str
    anonymized: bool
    template_url: str
    figure_guidelines: dict
    poster_size: Optional[str]
    deadline_month: Optional[int]
    areas: list[str]

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "full_name": self.full_name,
            "venue_type": self.venue_type,
            "page_limit": self.page_limit,
            "page_limit_with_refs": self.page_limit_with_refs,
            "paper_size": self.paper_size,
            "margins": self.margins,
            "font_family": self.font_family,
            "font_size": self.font_size,
            "columns": self.columns,
            "abstract_word_limit": self.abstract_word_limit,
            "citation_style": self.citation_style,
            "anonymized": self.anonymized,
            "template_url": self.template_url,
            "figure_guidelines": self.figure_guidelines,
            "poster_size": self.poster_size,
            "deadline_month": self.deadline_month,
            "areas": self.areas,
        }


CONFERENCES = {
    "neurips": ConferenceRequirements(
        name="neurips",
        full_name="Conference on Neural Information Processing Systems",
        venue_type="conference",
        page_limit=9,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=10,
        columns=2,
        abstract_word_limit=250,
        citation_style="neurips",
        anonymized=True,
        template_url="https://neurips.cc/Conferences/2024/PaperInformation/StyleFiles",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "png"],
            "width_single": 3.25,
            "width_double": 6.75,
            "font_size_min": 8,
        },
        poster_size="36x48 inches",
        deadline_month=5,
        areas=["ml", "ai", "deep_learning", "optimization", "theory"],
    ),
    "icml": ConferenceRequirements(
        name="icml",
        full_name="International Conference on Machine Learning",
        venue_type="conference",
        page_limit=8,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=10,
        columns=2,
        abstract_word_limit=200,
        citation_style="icml",
        anonymized=True,
        template_url="https://icml.cc/Conferences/2024/StyleAuthorInstructions",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "eps"],
            "width_single": 3.25,
            "width_double": 6.75,
            "font_size_min": 8,
        },
        poster_size="A0",
        deadline_month=1,
        areas=["ml", "deep_learning", "reinforcement_learning", "optimization"],
    ),
    "iclr": ConferenceRequirements(
        name="iclr",
        full_name="International Conference on Learning Representations",
        venue_type="conference",
        page_limit=9,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=10,
        columns=1,
        abstract_word_limit=250,
        citation_style="iclr",
        anonymized=True,
        template_url="https://iclr.cc/Conferences/2024/AuthorGuide",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "png"],
            "width_max": 5.5,
            "font_size_min": 8,
        },
        poster_size="A0",
        deadline_month=9,
        areas=["deep_learning", "representation_learning", "generative_models"],
    ),
    "cvpr": ConferenceRequirements(
        name="cvpr",
        full_name="IEEE/CVF Conference on Computer Vision and Pattern Recognition",
        venue_type="conference",
        page_limit=8,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 0.75, "right": 0.75},
        font_family="Times",
        font_size=10,
        columns=2,
        abstract_word_limit=300,
        citation_style="ieee",
        anonymized=True,
        template_url="https://cvpr.thecvf.com/Conferences/2024/AuthorGuidelines",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "eps", "png"],
            "width_single": 3.25,
            "width_double": 6.875,
            "font_size_min": 6,
        },
        poster_size="4x8 feet",
        deadline_month=11,
        areas=["cv", "recognition", "detection", "segmentation", "3d_vision"],
    ),
    "iccv": ConferenceRequirements(
        name="iccv",
        full_name="IEEE/CVF International Conference on Computer Vision",
        venue_type="conference",
        page_limit=8,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 0.75, "right": 0.75},
        font_family="Times",
        font_size=10,
        columns=2,
        abstract_word_limit=300,
        citation_style="ieee",
        anonymized=True,
        template_url="https://iccv2023.thecvf.com/author.guidelines-361600-2-20-16.php",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "eps", "png"],
            "width_single": 3.25,
            "width_double": 6.875,
            "font_size_min": 6,
        },
        poster_size="4x8 feet",
        deadline_month=3,
        areas=["cv", "3d_vision", "video", "recognition"],
    ),
    "eccv": ConferenceRequirements(
        name="eccv",
        full_name="European Conference on Computer Vision",
        venue_type="conference",
        page_limit=14,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=10,
        columns=1,
        abstract_word_limit=300,
        citation_style="springer",
        anonymized=True,
        template_url="https://eccv.ecva.net/Conferences/2024/SubmissionPolicies",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "eps"],
            "width_max": 5.5,
            "font_size_min": 8,
        },
        poster_size="A0",
        deadline_month=3,
        areas=["cv", "video", "medical_imaging", "recognition"],
    ),
    "acl": ConferenceRequirements(
        name="acl",
        full_name="Annual Meeting of the Association for Computational Linguistics",
        venue_type="conference",
        page_limit=8,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=11,
        columns=2,
        abstract_word_limit=200,
        citation_style="acl",
        anonymized=True,
        template_url="https://acl-org.github.io/ACLPUB/formatting.html",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "png"],
            "width_single": 3.0,
            "width_double": 6.5,
            "font_size_min": 8,
        },
        poster_size="A0",
        deadline_month=1,
        areas=["nlp", "computational_linguistics", "dialogue", "mt"],
    ),
    "emnlp": ConferenceRequirements(
        name="emnlp",
        full_name="Conference on Empirical Methods in Natural Language Processing",
        venue_type="conference",
        page_limit=8,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=11,
        columns=2,
        abstract_word_limit=200,
        citation_style="acl",
        anonymized=True,
        template_url="https://2024.emnlp.org/calls/main_conference_papers/",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "png"],
            "width_single": 3.0,
            "width_double": 6.5,
            "font_size_min": 8,
        },
        poster_size="A0",
        deadline_month=6,
        areas=["nlp", "information_extraction", "qa", "summarization"],
    ),
    "naacl": ConferenceRequirements(
        name="naacl",
        full_name="North American Chapter of the Association for Computational Linguistics",
        venue_type="conference",
        page_limit=8,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=11,
        columns=2,
        abstract_word_limit=200,
        citation_style="acl",
        anonymized=True,
        template_url="https://naacl.org/naacl-pubs/",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "png"],
            "width_single": 3.0,
            "width_double": 6.5,
            "font_size_min": 8,
        },
        poster_size="A0",
        deadline_month=12,
        areas=["nlp", "dialogue", "semantics", "multilingual"],
    ),
    "aaai": ConferenceRequirements(
        name="aaai",
        full_name="AAAI Conference on Artificial Intelligence",
        venue_type="conference",
        page_limit=7,
        page_limit_with_refs=8,
        paper_size="letter",
        margins={"top": 0.75, "bottom": 1.25, "left": 0.75, "right": 0.75},
        font_family="Times",
        font_size=10,
        columns=2,
        abstract_word_limit=150,
        citation_style="aaai",
        anonymized=True,
        template_url="https://aaai.org/authorkit24-2/",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "eps"],
            "width_single": 3.25,
            "width_double": 6.875,
            "font_size_min": 8,
        },
        poster_size="4x8 feet",
        deadline_month=8,
        areas=["ai", "planning", "reasoning", "knowledge_representation"],
    ),
    "ijcai": ConferenceRequirements(
        name="ijcai",
        full_name="International Joint Conference on Artificial Intelligence",
        venue_type="conference",
        page_limit=7,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 0.75, "bottom": 1.0, "left": 0.75, "right": 0.75},
        font_family="Times",
        font_size=10,
        columns=2,
        abstract_word_limit=200,
        citation_style="ijcai",
        anonymized=True,
        template_url="https://ijcai-24.org/call-for-papers/",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "eps"],
            "width_single": 3.25,
            "width_double": 6.875,
            "font_size_min": 8,
        },
        poster_size="A0",
        deadline_month=1,
        areas=["ai", "multiagent_systems", "robotics", "nlp"],
    ),
    "kdd": ConferenceRequirements(
        name="kdd",
        full_name="ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
        venue_type="conference",
        page_limit=9,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=9,
        columns=2,
        abstract_word_limit=200,
        citation_style="acm",
        anonymized=True,
        template_url="https://kdd.org/kdd2024/call-for-research-track-papers/",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "eps", "png"],
            "width_single": 3.33,
            "width_double": 7.0,
            "font_size_min": 8,
        },
        poster_size="4x3 feet",
        deadline_month=2,
        areas=["data_mining", "ml", "graph_learning", "recommender_systems"],
    ),
    "www": ConferenceRequirements(
        name="www",
        full_name="The Web Conference",
        venue_type="conference",
        page_limit=9,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=9,
        columns=2,
        abstract_word_limit=200,
        citation_style="acm",
        anonymized=True,
        template_url="https://www2024.thewebconf.org/calls/research-tracks/",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "eps", "png"],
            "width_single": 3.33,
            "width_double": 7.0,
            "font_size_min": 8,
        },
        poster_size="A0",
        deadline_month=10,
        areas=["web", "social_networks", "information_retrieval", "security"],
    ),
    "sigir": ConferenceRequirements(
        name="sigir",
        full_name="ACM SIGIR Conference on Research and Development in Information Retrieval",
        venue_type="conference",
        page_limit=9,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=9,
        columns=2,
        abstract_word_limit=200,
        citation_style="acm",
        anonymized=True,
        template_url="https://sigir-2024.github.io/call_for_papers.html",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "eps", "png"],
            "width_single": 3.33,
            "width_double": 7.0,
            "font_size_min": 8,
        },
        poster_size="A0",
        deadline_month=1,
        areas=["information_retrieval", "search", "recommender_systems", "nlp"],
    ),
    "chi": ConferenceRequirements(
        name="chi",
        full_name="ACM CHI Conference on Human Factors in Computing Systems",
        venue_type="conference",
        page_limit=10,
        page_limit_with_refs=None,
        paper_size="letter",
        margins={"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        font_family="Times",
        font_size=10,
        columns=2,
        abstract_word_limit=150,
        citation_style="acm",
        anonymized=True,
        template_url="https://chi2024.acm.org/for-authors/papers/",
        figure_guidelines={
            "dpi": 300,
            "format": ["pdf", "png", "jpg"],
            "width_single": 3.33,
            "width_double": 7.0,
            "font_size_min": 6,
        },
        poster_size="4x3 feet",
        deadline_month=9,
        areas=["hci", "user_studies", "accessibility", "visualization"],
    ),
}


def get_conference(name: str) -> Optional[ConferenceRequirements]:
    return CONFERENCES.get(name.lower())


def list_all_conferences() -> list[dict]:
    return [
        {
            "name": conf.name,
            "full_name": conf.full_name,
            "page_limit": conf.page_limit,
            "deadline_month": conf.deadline_month,
            "areas": conf.areas,
        }
        for conf in CONFERENCES.values()
    ]


def get_conferences_by_area(area: str) -> list[ConferenceRequirements]:
    return [conf for conf in CONFERENCES.values() if area.lower() in conf.areas]
